stages:
  - build_Linux
  - package
  - upload

variables:
  PLUGIN_NAME: "Figma2UMG"
  PLUGIN_PATH: "$CI_PROJECT_DIR/Plugins/Figma2UMG/Figma2UMG.uplugin"
  PACKAGE_DIR: "$CI_PROJECT_DIR/Release"
  UE_VERSIONS: "5.2 5.3 5.4 5.5"

build_plugin:
  stage: build_Linux
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$GitHubToken" | docker login ghcr.io -u "$GitHubUser" --password-stdin
  script:
    - |
      for VERSION in $UE_VERSIONS; do
        echo "Pulling Unreal Engine Docker image for $VERSION"
        docker pull ghcr.io/epicgames/unreal-engine:dev-${VERSION}
        echo "Building for Unreal Engine $VERSION"
        docker run --rm -v "$CI_PROJECT_DIR:/project" ghcr.io/epicgames/unreal-engine:dev-${VERSION} \
          /bin/bash -c "/home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh BuildPlugin \
          -Plugin=/project/Plugins/Figma2UMG/Figma2UMG.uplugin \
          -Package=/project/Release/${VERSION}_Linux \
          -Rocket -TargetPlatforms=Linux"
      done

package:
  stage: package
  script:
    - DATE=$(date +%Y-%m-%d)
    - mkdir -p "Zips/$DATE"
    - |
      for VERSION in $UE_VERSIONS; do
        ZIP_NAME="Figma2UMG-${VERSION}.zip"
        zip -r "Zips/$DATE/$ZIP_NAME" "Release/${VERSION}_Linux"
      done
  artifacts:
    paths:
      - Zips/

upload:
  stage: upload
  image: google/cloud-sdk:alpine
  before_script:
    - echo "$GCP_SERVICE_ACCOUNT_KEY" > /tmp/key.json
    - gcloud auth activate-service-account --key-file=/tmp/key.json
    - gcloud config set project "$GCP_PROJECT_ID"
  script:
    - DATE=$(date +%Y-%m-%d)
    - for FILE in Zips/$DATE/*.zip; do
        BASENAME=$(basename "$FILE")
        gsutil cp "$FILE" "gs://$GCS_BUCKET_NAME/$DATE/$BASENAME"
      done
  only:
    - main
